; Super Mario Galaxy VR - menu (B + Y). Index of the chosen value per option.
walk=1
movie=0
fp=1
body=1
arms=1
snap=0
markers=0
camdist2=14
autocenter=0
flipcam=0
glove=1
hud=2
menuback=1
bodyscale=0
world=0
eyeoff3=26
camfwd3=26
handfwd3=16
handup3=16
music=1
tplevel=1
tpelev=10
tpdist=4
tpheight=6
cull2=2
tpsmooth=2
fps2=0
pitch=9
movefwd=8
