; Super Mario Galaxy VR - menu (B + Y). Index of the chosen value per option.
walk=1
movie=0
fp=1
body=1
arms=1
snap=0
markers=1
camdist2=22
autocenter=0
flipcam=1
glove=2
hud=0
menuback=1
bodyscale=0
world=0
eyeoff3=24
camfwd3=31
handfwd3=16
handup3=16
